Update infra.yml

diff --git a/.github/workflows/infra.yml b/.github/workflows/infra.yml
--- a/.github/workflows/infra.yml
+++ b/.github/workflows/infra.yml
@@ -43,42 +43,42 @@ jobs:
         with:
           terraform_version: 1.5.5
 
-      - name: Install TFLint
-        run: |
-          TFLINT_VERSION="v0.55.0"
-          curl -sL "https://github.com/terraform-linters/tflint/releases/download/${TFLINT_VERSION}/tflint_linux_amd64.zip" -o tflint.zip
+      # - name: Install TFLint
+      #   run: |
+      #     TFLINT_VERSION="v0.55.0"
+      #     curl -sL "https://github.com/terraform-linters/tflint/releases/download/${TFLINT_VERSION}/tflint_linux_amd64.zip" -o tflint.zip
           
-          if [ ! -s "tflint.zip" ]; then
-            echo "Error: Downloaded TFLint archive is empty or invalid."
-            exit 1
-          fi
+      #     if [ ! -s "tflint.zip" ]; then
+      #       echo "Error: Downloaded TFLint archive is empty or invalid."
+      #       exit 1
+      #     fi
 
-          unzip tflint.zip
-          chmod +x tflint
-          sudo mv tflint /usr/local/bin/
-          rm tflint.zip
+      #     unzip tflint.zip
+      #     chmod +x tflint
+      #     sudo mv tflint /usr/local/bin/
+      #     rm tflint.zip
           
-          echo "TFLint installed successfully:"
-          tflint --version
+      #     echo "TFLint installed successfully:"
+      #     tflint --version
 
-      - name: Run TFLint
-        run: |
-         cd ./infra/environments/${{ github.event.inputs.environment || 'dev' }}
+      # - name: Run TFLint
+      #   run: |
+      #    cd ./infra/environments/${{ github.event.inputs.environment || 'dev' }}
 
-         # Ensure .tflint.hcl exists
-         if [ ! -f ".tflint.hcl" ]; then
-            cat <<EOF > .tflint.hcl
-            plugin "terraform" {
-            enabled = true
-           }
-         EOF
-         fi
+      #    # Ensure .tflint.hcl exists
+      #    if [ ! -f ".tflint.hcl" ]; then
+      #       cat <<EOF > .tflint.hcl
+      #       plugin "terraform" {
+      #       enabled = true
+      #      }
+      #    EOF
+      #    fi
 
-         # Install TFLint plugin (Terraform)
-         tflint --init
+      #    # Install TFLint plugin (Terraform)
+      #    tflint --init
 
-         # Run TFLint with proper syntax
-         tflint --config .tflint.hcl
+      #    # Run TFLint with proper syntax
+      #    tflint --config .tflint.hcl
 
       # Step: Install Checkov
       - name: Install Checkov
@@ -110,43 +110,43 @@ jobs:
           cd ./infra/environments/${{ github.event.inputs.environment || 'dev' }}
           terraform plan 
 
-      # Step: Checkout Repository for PR
-      - name: Checkout Repository
-        uses: actions/checkout@v3
-        with:
-          fetch-depth: 0
-          ref: ${{ github.event.pull_request.head.ref || github.ref }} 
-          token: ${{ secrets.PAT_TOKEN }}
+      # # Step: Checkout Repository for PR
+      # - name: Checkout Repository
+      #   uses: actions/checkout@v3
+      #   with:
+      #     fetch-depth: 0
+      #     ref: ${{ github.event.pull_request.head.ref || github.ref }} 
+      #     token: ${{ secrets.PAT_TOKEN }}
 
-      # Step: Configure Git for committing generated README.md
-      - name: Configure Git
-        run: |
-          git config --global user.name 'github-actions[bot]'
-          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
+      # # Step: Configure Git for committing generated README.md
+      # - name: Configure Git
+      #   run: |
+      #     git config --global user.name 'github-actions[bot]'
+      #     git config --global user.email 'github-actions[bot]@users.noreply.github.com'
 
-      # Step: Generate Markdown with Terraform Docs
-      - name: Generate Markdown with Terraform Docs
-        if: ${{ github.event_name == 'pull_request' }}
-        uses: terraform-docs/gh-actions@v1.3.0
-        with:
-          working-dir: ./infra/environments/${{ github.event.inputs.environment || 'dev' }}
-          output-file: README.md
-          output-method: inject
-          git-push: true
-          config-file: .terraform-docs.yml
+      # # Step: Generate Markdown with Terraform Docs
+      # - name: Generate Markdown with Terraform Docs
+      #   if: ${{ github.event_name == 'pull_request' }}
+      #   uses: terraform-docs/gh-actions@v1.3.0
+      #   with:
+      #     working-dir: ./infra/environments/${{ github.event.inputs.environment || 'dev' }}
+      #     output-file: README.md
+      #     output-method: inject
+      #     git-push: true
+      #     config-file: .terraform-docs.yml
 
-      # Add README.md to PR Comment using Sticky Comment
-      - name: Post README.md as PR Comment
-        if: ${{ github.event_name == 'pull_request' }}
-        uses: marocchino/sticky-pull-request-comment@v2.9.0
-        with:
-          github_token: ${{ secrets.GITHUB_TOKEN }}
-          header: "Terraform Documentation "
-          path: "./infra/environments/${{ github.event.inputs.environment || 'dev' }}/README.md"
+      # # Add README.md to PR Comment using Sticky Comment
+      # - name: Post README.md as PR Comment
+      #   if: ${{ github.event_name == 'pull_request' }}
+      #   uses: marocchino/sticky-pull-request-comment@v2.9.0
+      #   with:
+      #     github_token: ${{ secrets.GITHUB_TOKEN }}
+      #     header: "Terraform Documentation "
+      #     path: "./infra/environments/${{ github.event.inputs.environment || 'dev' }}/README.md"
     
       # Step: Apply Terraform if PR is merged
       - name: Apply Terraform on Merge the PR
-        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
+        # if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
         run: |
           cd ./infra/environments/${{ github.event.inputs.environment || 'dev' }}
           terraform init
